version: "3"
services:
 db:
  image: mysql:latest
  container_name: db
  ports:
   - 3306:3306
  volumes:
   - ./mysql_data:/var/lib/mysql
   - ./data/simple-docker-php.sql:/docker-entrypoint-initdb.d/simple-docker-php.sql
  environment:
   MYSQL_ROOT_PASSWORD: 12345
   MYSQL_DATABASE: simple_db
   MYSQL_USER: user
   MYSQL_PASSWORD: password
 app:
  image: alexeychusta/simple-php
  container_name: application
  ports:
   - 8080:80
  restart: always
  depends_on:
   - db

