version: "3"
services:
 db:
  image: mysql:latest
  container_name: db
  ports:
   - 3306:3306
  volumes:
   - ./mysql_data:/var/lib/mysql
   - ./data/simple-docker-php.sql:/docker-entrypoint-initdb.d/simple-docker-php.sql
  env_file:
   - ./etc/mysql/users.env
   - ./etc/mysql/root_user.env
   - ./etc/mysql/db.env
 app:
  image: alexeychusta/simple-php-app:${TAG}
  container_name: app
  env_file:
   - ./etc/mysql/users.env
   - ./etc/mysql/db.env
  ports:
   - 8080:80

  restart: always
  depends_on:
   - db
 nginx:
  image: nginx:1.19.3-alpine
  container_name: nginx
  volumes:
   - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
  ports:
   - 80:80
  depends_on:
   - app


